services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=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
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    volumes:
      - ./backend/src:/app/src
      - ./models:/app/src/ml/models

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  elasticsearch-data: